name: If condition demo
on:
  push:
    branches:
      - main
      - develop
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run this step
        if: github.ref == 'refs/heads/main'
        run: echo "Running for the main branch"
       - name: Run this step
        run: echo "Running this step"
        
