name: Inputs Demo Env
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
      artifact_tag:
        description: choose the git tag to deploy
        required: true
      
jobs:
  inputs-demo-env:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "Deploying the ${{ inputs.artifact_tag }} application to ${{ inputs.environment }}"
