name: parallel-workflow
on: wworkflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Build Step"

  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "Test Step"
  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "Deploy Step"
